approvedGitRepositories:
  - "**"

enableScripts: false

enableStrictSsl: true

enableTelemetry: false

networkSettings:
  registry.npmjs.org:
    enableNetwork: true
  registry.yarnpkg.com:
    enableNetwork: true

nodeLinker: pnpm

yarnPath: .yarn/releases/yarn-4.18.0.cjs
