name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2

jobs:
  cypress-run:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        browser: [electron]
        os: [ubuntu-latest]
        vpi: ['8.0.0', '9.0.1']
    env:
      COVERAGE: true
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '22.x'
          cache: yarn

      - name: Install dependencies
        run: yarn add --dev -E 'vite-plugin-istanbul@${{ matrix.vpi }}'

      - name: Test (E2E)
        uses: cypress-io/github-action@v7
        env:
          BASE_URL: http://localhost:4173/
        with:
          spec: tests/e2e/specs/alert.cy.js
          build: yarn run build --mode offline --minify false
          start: yarn run preview
          config: baseUrl=${{ env.BASE_URL }}
          wait-on: ${{ env.BASE_URL }}
          browser: ${{ matrix.browser }}

      - name: Inspect nyc output
        run: |
          cat .nyc_output/out.json

      - name: Inspect coverage info
        run: |
          cat coverage/lcov.info
